examples/test_lda.ml
lib/topic/owl_topic_lda.ml

Inital implementation of the Sparse LDA algorithm. 
More work is needed to realise the full performance benefits. This includes using an alias table and a more efficient structure for storing non-zero probability factors.

Sparse LDA 

---

lib/owl_dense_ndarray.ml
lib/owl_dense_ndarray.mli

I added two map functions for Dense.Ndarray module.

add map2i and map2 for ndarray

---

lib/owl_stats.ml
lib/owl_stats.mli

Previously ties were always resolve using averaging.

Added explicit ties strategy to 'Owl_stats.rank'

---

examples/owl_plot_examples.ml
lib/owl_plot.ml
lib/owl_plot.mli

This is for issue #57.
I added a bit of text to the doc comments in the mli file.  Not sure if that's more than you want there.
The commit history is kind of odd looking (to me, at least).  Not worth explaining.

Add option to spec for plplot 3D options plus code to use it

---

lib/owl_plot.ml
lib/owl_plot.mli

Sorry for this late PR. Here is what it contains:
1. in the new version, `semilogx` and `semilogy` are only special cases of `loglog`, to which I  added an `axis` parameter.
2. Add a image plot. Please see here ([code](https://gist.githubusercontent.com/jzstark/9f49c77626533fb8e84a5131f67d4e05/raw/80da435d38312de63bb841a5af61853c88571775/examples.ml), [figure](https://gist.githubusercontent.com/jzstark/9f49c77626533fb8e84a5131f67d4e05/raw/80da435d38312de63bb841a5af61853c88571775/plot_026.png)) for an example. To remove the ticks/labels around the image, I add a `is_image` property to `page` in order for `_config_2d_axis` to return the proper code -1.

update log plot and add image plot

---

lib/owl_plot.ml
lib/owl_plot.mli

Reverts ryanrhymes/owl#71
still buggy.

Revert "fix image plot bug"

---

examples/test_mnist2.ml
lib/owl_plot.ml

Thanks for pointing it out. The updated plot can be viewed [here](https://gist.githubusercontent.com/jzstark/dec579b428c5a0109e3900d80117b627/raw/a70b96e62818427f9f0a94ce5f46927038e3cf43/qqplot.png).

set line style back after drawing extendline prob/qqplot

---

lib/owl_dense_matrix_generic.ml
lib/owl_dense_matrix_generic.mli
unittest/unit_dense_matrix.ml

This adds some functionality to compute the Kronecker product between to matrices of type float. @ryanrhymes I have some troubles making this fully generic. Maybe you can offer some advice?

Matrix kron

---

CONTRIBUTING.md
lib/neural/owl_neural_neuron.ml
lib/owl_dataset.ml
lib/owl_dense_matrix_generic.mli
lib/owl_dense_ndarray_generic.mli

Here is a summary of this PR:
- fix shape inconsistency issues for some neuron
- add a `draw_samples_cifar` function in `Dataset`
- update `CONTRIBUTE.md` 
- update doc of `scalar_*` functions of matrix and ndarray

update neuron and doc

---

lib/owl_dense_matrix_generic.mli
lib/owl_dense_ndarray_generic.mli

Use more precise words in describing the scalar_* and *_scalar functions.

minor fix of mat/arr doc

---

CONTRIBUTING.md
lib/owl_dense_matrix_generic.ml

A summary of this PR: 
- Fix one bug in the `std` function of matrix: the denominator should be sqrt-ed before being used
- A minor update of `CONTRIBUTING.md`

fix Mat.std function

---

owl.opam
owl_top.opam
owl_zoo.opam

* add jbuilder as a dependency
* remove package names from opam files
* add build-test command

Fix opam metadata

---

src/owl/owl_dense_matrix_generic.mli
src/owl/owl_dense_ndarray_generic.mli
src/owl/owl_linalg_generic.mli

Liang--I can't squash commits.  It looks like there's something that you have to enable in order for others to be able to squash:
https://github.com/blog/2141-squash-your-commits
(I tried to squash in git following these instructions:
https://gist.github.com/patik/b8a9dc5cd356f9f6f980
It didn't work; now I have two different commits for the exact same changes, plus an irrelevant merge. :-)

In docs for inv, added note about singular matrices

---

src/owl/stats/owl_stats.mli

a minor test, updated owl's doc on `histogram`

update owl document

---

src/owl/maths/owl_maths_root.ml
src/owl/stats/owl_stats.mli

I have added three basic root finding algorithms: bisection, false position, and ridder algorithms. Please have a look. If this is ok, I can add mli file later. 
I currently PR to the core library rather than the base library, but you can decide where to put these functions. 
Thanks.

Add basic root finding algorithms

---

src/owl/jbuild
src/owl/maths/owl_maths_root.ml
src/owl/maths/owl_maths_root.mli
src/owl/stats/owl_stats.mli

This PR includes the implementation of Brent algorithm. I also fixed some documentation in the Stats module.

Add Brent method for root finding

---

src/owl/maths/owl_maths_root.ml
src/owl/maths/owl_maths_root.mli
test/unit_maths_root.ml

In this PR, I have included a helper function for root-finding algorithms, more specifically for expanding bracket. I also included unit tests for the root-finding algorithms.

Helper function and unit test for Root finding

---

src/owl/stats/owl_stats.mli

These are some docs for the discrete RV functions.   I'd be happy to revise either content and style.  Among other things, please check that the semantics are correct.  I wasn't familiar with all of the distributions, so I looked up info about some of them and had to guess about some of the parameters.  (I did try to find the source for some of the functions, but understanding the C source code for these functions wasn't trivial for me.)

Discrete rv docs

---

.travis.yml
CHANGES.md
Dockerfile
Makefile
owl-base.opam
owl-top.opam
owl-zoo.opam
owl.opam
pkg/.merlin
pkg/pkg.ml

Hopefully fixes the Dockerfile used by Travis.
Also adds some `topkg` runes per Daniel's multi-package example and Thomas' `topkg-jbuilder` extension. This is certainly not ideal but is probably an improvement for now. I'll pick it up with Daniel and Thomas to see if there's a better way.

Fix travis

---

.travis.yml
owl.opam
src/owl/config/configure.ml

I believe this fixes configure process to the extent that it should now work on Ubuntu et al.

Fix configure

---

.travis.yml
CHANGES.md
Makefile
README.md
owl-base.opam
owl-top.opam
owl-zoo.opam
src/owl/config/configure.ml

* fix URLs in README
* fix OPAM files to match release in opam-repository
* correct date in CHANGELOG for 0.3.7 release
* Makefile tweaks

Misc cleanups

---

CHANGES.md

Signed-off-by: Richard Mortier <mort@cantab.net>

changelog: prep for release

---

src/owl/maths/owl_maths.mli

this should make the math display in html generated docs look nicer

updated owl_maths.mli with :math: annotations

---

Makefile

cosmetic change
Signed-off-by: Hiroshi Doyu <hiroshi.doyu@ericsson.com>

less noisy installation message

---

src/owl/cblas/owl_cblas_basic.ml

This PR corrects a copy/paste bug discovered when running tests with #290.

use explicit labels in owl_cblas_basic

---

.travis.yml

This should fix the current Travis build errors.

travis: Use the original ocaml-ci-scripts script

---

src/owl/core/owl_ndarray_conv_impl.h

This PR fixes a bug in convolution operation implementation that is caused by multiplication overflow.

Fix convolution operation bug

---

src/base/maths/owl_base_maths.ml
src/base/maths/owl_base_maths.mli
src/owl/maths/owl_maths.ml
src/owl/maths/owl_maths.mli
test/unit_maths.ml

Finishes the incomplete is_prime function. The algorithm used is the Miller-Rabin primality test with bases that make it deterministic for all integers that an OCaml int can represent.

Finish the is_prime function

---

src/base/compute/owl_computation_cpu_init.ml

Modify the `split_parents` function in `owl_computation_cpu_init.ml` to make it more similar to the other CG files, to be easier to optimise and to generate a compilation error if a new operation is added without changing this file.
Fix the status of `Reverse` and the `TransposeConvNd` operations (cannot overwrite their parents) + very small optimisation for `Concatenate`. I have added a comment next to the operations that might maybe overwrite some of their parents depending on their parameters, in case the person who implemented them wants to think about it :)

Clean split_parents function in CG cpu_init

---

src/owl/core/owl_ndarray_conv_impl.h

This PR adds support for more CPU infrastructures when checking L1/L2/L3 cache sizes, which affect the convolution computation.

Fix cache size check

---

docker/Dockerfile.alpine
docker/Dockerfile.centos
docker/Dockerfile.fedora
docker/Dockerfile.opensuse
src/aeos/config/configure.ml
src/aeos/config/dune
src/aeos/dune

This PR adds a configuration file trying to address #335. This config file is similar to [src/owl/config](https://github.com/owlbarn/owl/tree/master/src/owl/config), with smaller number of compiling options. 
I've tested compiling Owl on MacOS, RaspberryPi, Ubuntu, and several docker containers. Current Dockerfiles are therefore also fixed in this PR.

Add configuration file for aeos module and update Dockerfiles

---

src/base/stats/owl_base_stats.ml
src/owl/stats/owl_stats.ml
src/owl/stats/owl_stats.mli
test/unit_stats.ml

Here's a proposition for #341, I'm not too sure about the syntax for documentation, it seems it is different from the usual `ocamldoc` syntax, right?

stats: optimisation of quantile for repeated calls (#341)

---

examples/tf_convert.ml
owl-converter.opam
src/tf_converter/Owl_converter_utils.ml
src/tf_converter/dune
src/tf_converter/example.ml
src/tf_converter/owl_converter.ml
src/tf_converter/owl_converter_attr.ml
src/tf_converter/owl_converter_attr.mli
src/tf_converter/owl_converter_collection.ml
src/tf_converter/owl_converter_db.ml
src/tf_converter/owl_converter_db.mli
src/tf_converter/owl_converter_graph.ml
src/tf_converter/owl_converter_meta.ml
src/tf_converter/owl_converter_saver.ml
src/tf_converter/owl_converter_types.ml

Current progress on framework coding

TF CGraph converter 

---

docker/Dockerfile.ubuntu

Other Linux distribution could do the same.
Signed-off-by: Hiroshi Doyu <hiroshi.doyu@ericsson.com>

docker: fix eigen installation

---

.travis.yml
src/base/core/owl_lazy.mli
src/base/dense/owl_base_dense_ndarray_d.mli
src/base/dense/owl_base_dense_ndarray_generic.ml
src/base/dense/owl_base_dense_ndarray_generic.mli
src/base/dense/owl_base_dense_ndarray_s.mli
src/owl/config/configure.ml
src/owl/dune
test/unit_lazy.ml

* autodiscover openblas via pkg-config if possible (especially useful if you provide a specific PKG_CONFIG_PATH)
* check if lapacke is needed (hopefully enough to fix the build)

Owl cleanup configure part1

---

owl-plplot.opam

owl-plplot: add missing dependency

---

README.md

README: point to examples for build flags override

---

bin/owl_bin_zoo.ml
src/zoo/owl_zoo_cmd.ml
src/zoo/owl_zoo_cmd.mli

This PR fixes zoo so that `owl -run` accepts extra parameters now.

Add parameter support to Zoo

---

test/unit_algodiff_diff_generic.ml
test/unit_algodiff_grad_generic.ml
test/unit_algodiff_matrix_generic.ml
test/unit_conv2d_generic.ml
test/unit_dense_matrix.ml
test/unit_dense_ndarray.ml
test/unit_sparse_matrix.ml
test/unit_sparse_ndarray.ml
test/unit_stats_rvs.ml

I did my best to understand the context of each warning and check there was no bug lurking behind. I only found one case where some code was actually dead (and a test case was consequently ignored). All tests pass after this correction.

Fix test warnings

---

src/base/core/owl_exception.ml
src/base/core/owl_exception.mli
src/owl/dense/owl_dense_ndarray_generic.ml

New exception design in Owl

---

src/base/dense/owl_base_dense_ndarray_generic.ml

Following previous PR, this one updates the assertions in convolution operations into informative exceptions.

Update base_conv exceptions

---

src/base/misc/owl_io.ml
src/base/misc/owl_io.mli
src/base/neural/owl_neural_graph.ml
src/base/neural/owl_neural_graph_sig.ml

I've implemented the solution that @clecat and @mseri suggested in #425, to solve the problem of saving networks that contain Lambda layer.

Add unsafe network save

---

src/base/linalg/owl_base_linalg_generic.ml

This minor PR fixes #465 by replacing the `exit` with exceptions. Thanks for the help from @mseri !

Fix: replace exit with exception 

---

src/owl/core/owl_ndarray_conv_impl.h
src/owl/core/owl_ndarray_conv_stub.c
test/unit_conv2d_generic.ml

A temporary workaround to the issue #477 . Also add new unit test accordingly.

Temporary workaround to convolution bug 

---

src/owl/dense/owl_dense_matrix_generic.mli
src/owl/dense/owl_dense_matrix_intf.ml
src/owl/dense/owl_dense_ndarray_generic.ml
src/owl/dense/owl_dense_ndarray_generic.mli
src/owl/dense/owl_dense_ndarray_intf.ml

As raised in #488 , I added `sem` and `sem'` to the Dense Ndarray and Dense Matrix modules.

add sem to dense ndarray and matrix

---

src/base/dense/owl_base_dense_ndarray_generic.ml
src/base/dense/owl_base_dense_ndarray_generic.mli
src/base/dense/owl_base_dense_ndarray_intf.ml
src/owl/dense/owl_dense_ndarray_generic.ml
src/owl/dense/owl_dense_ndarray_generic.mli
test/unit_dense_ndarray.ml

added `stack` function to Ndarray modules as discussed in #505

added stack function

---

src/base/algodiff/owl_algodiff_ops.ml
src/base/algodiff/owl_algodiff_ops_sig.ml
src/base/compute/owl_computation_cpu_init.ml
src/base/compute/owl_computation_operator.ml
src/base/compute/owl_computation_operator_sig.ml
src/base/compute/owl_computation_shape.ml
src/base/compute/owl_computation_symbol.ml
src/base/compute/owl_computation_type.ml
src/base/compute/owl_computation_type_sig.ml
src/base/dense/owl_base_dense_ndarray_generic.ml
src/base/dense/owl_base_dense_ndarray_generic.mli
src/base/dense/owl_base_dense_ndarray_intf.ml
src/base/types/owl_types_ndarray_basic.ml
src/owl/dense/owl_dense_matrix_generic.mli
src/owl/dense/owl_dense_matrix_intf.ml
src/owl/dense/owl_dense_ndarray_generic.ml
src/owl/dense/owl_dense_ndarray_generic.mli
src/owl/dense/owl_dense_ndarray_intf.ml
test/unit_algodiff_matrix_generic.ml

1. added `log_sum_exp` along an axis to Ndarray
2. added `log_sum_exp` and `log_sum_exp'` to Algodiff

added log_sum_exp to Ndarray and Algodiff

---

src/base/algodiff/owl_algodiff_ops.ml
src/base/algodiff/owl_algodiff_ops_sig.ml
src/base/compute/owl_computation_cpu_init.ml
src/base/compute/owl_computation_operator.ml
src/base/compute/owl_computation_operator_sig.ml
src/base/compute/owl_computation_symbol.ml
src/base/compute/owl_computation_type.ml
src/base/compute/owl_computation_type_sig.ml
src/base/types/owl_types_ndarray_basic.ml
test/unit_algodiff_matrix_generic.ml

Added `stack` function to Algodiff `Maths`

Add stack to Algodiff

---

src/aeos/owl_aeos_utils.ml
src/base/misc/owl_io.ml
src/opencl/bindings/owl_opencl_parser.ml
src/opencl/config/make_kernel.ml
src/owl/bindings/owl_cblas_parser.ml
src/owl/bindings/owl_lapacke_parser.ml
src/owl/core/owl_ndarray_maths.ml
src/owl/dense/owl_dense_matrix_generic.ml
src/owl/dense/owl_dense_matrix_generic.mli
src/owl/dense/owl_dense_ndarray_generic.ml
src/owl/dense/owl_dense_ndarray_generic.mli
src/owl/nlp/owl_nlp_corpus.ml
src/owl/nlp/owl_nlp_tfidf.ml
src/owl/nlp/owl_nlp_utils.ml
src/owl/nlp/owl_nlp_vocabulary.ml
src/owl/stats/owl_stats.ml
src/owl/stats/owl_stats.mli

This should fix 
- https://github.com/owlbarn/owl/issues/514
- https://github.com/owlbarn/owl/issues/521
- https://github.com/owlbarn/owl/issues/522
- https://github.com/owlbarn/owl/issues/459
This PR was done during the time that I had allocated for the Owl meeting sponsored by the OCaml Software Foundation, postponed to a future date due to the COVID-19 outbreak.

Fix some open issues

---

src/base/algodiff/owl_algodiff_generic.ml
src/base/optimise/owl_optimise_generic_sig.ml

This PR allows us to differentiate through the Jacobian.

Jacobian is now differentiable

---

Dockerfile

I simply copied docker/Dockerfile.ubuntu to overwrite the one in root directory, so we can fix docker hub build.

Fix Dockerfile for master

---

src/owl/core/owl_ndarray_conv_impl.h

Convolution bug fix

---

src/base/algodiff/owl_algodiff_ops.ml
src/base/algodiff/owl_algodiff_ops_sig.ml
src/base/compute/owl_computation_cpu_init.ml
src/base/compute/owl_computation_operator.ml
src/base/compute/owl_computation_operator_sig.ml
src/base/compute/owl_computation_symbol.ml
src/base/compute/owl_computation_type.ml
src/base/compute/owl_computation_type_sig.ml
src/base/dense/owl_base_dense_ndarray_generic.ml
src/base/dense/owl_base_dense_ndarray_generic.mli
src/base/dense/owl_base_dense_ndarray_intf.ml
src/base/types/owl_types_ndarray_basic.ml
test/unit_algodiff_matrix_generic.ml

In this PR, I added `get_fancy` and `set_fancy` to Algodiff. 
I've also added unit tests for `get_slice` and `get_fancy`.

added get_fancy amd set_fancy to the algodiff library

---

.ocamlformat
src/base/algodiff/owl_algodiff_ops.ml
src/base/compute/owl_computation_shape.ml
src/base/linalg/owl_base_linalg_generic.ml
src/base/linalg/owl_base_linalg_intf.ml
src/base/stats/owl_base_stats.ml
src/owl/config/configure.ml
src/owl/fftpack/owl_fft_generic.ml

This is a preview of the not-yet-released ocamlformat.0.17.0, please wait until the package is published in opam to merge this PR.

Preview: upgrade to ocamlformat.0.17.0

---

src/owl/dense/owl_dense_ndarray_generic.ml

fix bug in split

---

.ocamlformat
src/base/compute/owl_computation_operator.ml
src/owl/dune
src/owl/signal/owl_signal.ml
src/owl/signal/owl_signal.mli
test/test_runner.ml
test/unit_signal.ml

This is a preview of the not-yet-released `ocamlformat.0.19.0`, please wait until the package is published in opam to merge this PR. The output is still likely to slightly change before the package is released.

[Preview] Upgrade to ocamlformat.0.19.0

---

src/base/dense/owl_base_dense_ndarray_generic.ml
src/owl/cblas/owl_cblas.ml
src/owl/dense/owl_dense_matrix_generic.ml
src/owl/dense/owl_dense_ndarray_generic.ml
src/owl/lapacke/owl_lapacke.ml

This PR would fix issue https://github.com/owlbarn/owl/issues/594
It probably needs some discussion first, whether this is the right way to fix the mentioned compiler warnings.

suppress warning 16

---

Makefile
README.md
src/owl/config/configure.ml
src/owl/core/owl_ndarray_conv_impl.h
src/owl/working/owl_parallel.ml
src/zoo/owl_zoo_cmd.ml
src/zoo/owl_zoo_dir.ml

Initial PR to migrate to OCaml 4.14. Please comment or suggest changes. Thanks.

Migrate to OCaml 4.14

---

INSTALL.md
src/aeos/config/configure.ml
src/owl/config/configure.ml
src/owl/core/owl_core_utils.c
src/owl/core/owl_macros.h
test/unit_signal.ml

Thanks @jhgorse for the help!
Should fix #597, I tested this on an iMac M1 and my Macbook Pro, but it would be good if somebody else could test it as well.

Add support for ARM64

---

src/base/neural/owl_neural_neuron.ml
src/base/neural/owl_neural_neuron_sig.ml

See https://www.tensorflow.org/api_docs/python/tf/keras/initializers/HeNormal

Add the NeNormal initializer

---

src/owl/core/owl_ndarray_maths_stub.c
test/unit_dense_ndarray.ml

This changes the definition of ssqr_diff' so that it does not mutate the inputs. Two tests are added for correctness and to check that it does not mutate the inputs. This addresses #645.

Changed def of ssqr_diff' to not modify inputs. Added two tests.

---

src/owl/config/configure.ml

remove -Ofast, -ffast-math

---

src/owl/dense/owl_dense_ndarray_generic.ml

owl_dense_ndarray_generic: fix implementation of not_equal_scalar
