lib/owl_plot.ml, lib/owl_plot.mli
Proposed solution to issue #47:
Added `altitude` and `azimuth` fields to the `page` type (`alt` and `az` here: http://plplot.sourceforge.net/docbook-manual/plplot-html-5.12.0/plw3d.html).  These  control the perspective from which `mesh` and `surf` plots are viewed.  
The two fields are initialized to default values in `_create_page` and are passed to `plw3d` in `_prepare_page`.
Also added functions `set_altitude` and `set_azimuth` to set the values using a `handle`, and added optional arguments to `mesh` and `surf` to specify altitude and azimuth.
=> owl_plot.ml,mli: add altitude, azimuth to page, 3D plot functions

lib/owl_plot.ml, lib/owl_plot.mli
Thank for pointing out this problem. As you may have found out, the input matrix need to be transposed to be positioned correctly. I will also update/rotate the example file `durer.txt` (which is actually now a 600 * 900 matrix) accordingly.
=> fix image plot bug

lib/owl_plot.ml
So sorry for the untested PR.  Here is how I propose to fix this problem and why:
If we `image` the input matrix as is, it will recognise the top left corner of the matrix as origin, with x-axis along rows and y-axis along columns, which is exactly how a matrix locate its elements. So I rotate the input matrix 90 degree clockwise (I failed to find a `Mat.rotate` or similar function from the doc so just implement a simple one) and then plot it as image.   I test with the code:
```ocaml
let z0 = Mat.create 100 100 200. in
let z1 = Mat.zeros 100 100 in
let z = Mat.((z1 @|| z0) @= (z1 @|| z1) @= (z1 @|| z1)) in
Plot.image z
```
The white rectangle (though not a square as we expected  --- I'll look into this problem later) is correctly shown on the upper left corner.
=> fix image-flip bug of imageplot

lib/owl_dense_common_c.c, unittest/unit_dense_ndarray.ml
When calculating the squared L2 norm of complex vectors the result can be negative giving rise to `NaN` when taking the `sqrt`. L2 norms are positive-semidefinite at all times. This fix adjusts the accumulator function for the L2 norm of complex numbers.
* Adjust accumulator for complex numbers
* Add unit test for complex vector
=> Fixing `l2norm` for complex arrays

lib/owl_fft.ml
The latest GSL release packages the library differently (using `jbuilder`), making it incompatible with Owl.  `Gsl_fft` was never supposed to be accessible, but leaked through anyway.  The correct way is to always use `Gsl.?` for accessing parts of the packed library.
=> Fixed module paths to Gsl.Fft

src/owl/owl_plot.ml, src/owl/owl_plot.mli
Identical to `area` but with four lines deleted, and a new doc comment.
I think I'm going to try also doing a second PR that's the same but that pulls out the code that `area` and `draw_polygon` into an internal function.  If github will allow two separate PRs (??), then you can choose.
(I understand the value of having different functions that duplicate code.  It's simpler to understand, and if you want to change one but not the other, it's easier.  However, in this case `draw_polygon` really is `area` with four lines deleted, so maybe it's reasonable to have them call the same internal function to run the code that's the same in both functions.)
This is in response to #107.
=> added draw_polygon

src/owl/owl_plot.ml, src/owl/owl_plot.mli
plot, loglog: added parentheses around let in 'if marker'
In the closure definition in `plot`, because the `let` in scope of `if marker ...` wasn't wrapped in parentheses, the `let` extended to the rest of the closure, and nothing else got executed if the `if` test failed. It's also clear from the indentation that this isn't what was intended.  Plot settings weren't getting rrestored to their previous values at the end of the closure, which caused some of the settings to carry over to the next closure when it was executed.
This fixes issue #113.  I don't know why the PR includes some old commits from my previous PR.  Let me know if I need to redo this one.
It seems clear that the same problem exists in loglog, so I fixed that. (EDIT: At first I couldn't run `loglog` just to test that I …
=> Fix bug in plot, loglog: let within if was capturing rest of closure

bin/jbuild, src/ocaml/jbuild, src/owl/jbuild, src/owl/owl_dense_common.ml, src/owl/owl_nlp_corpus.ml, src/owl/owl_nlp_vocabulary.ml, src/owl/owl_pretty.mli, src/top/jbuild, src/zoo/jbuild, test/jbuild
OCaml 4.06.0 uses `-safe-string` by default and so we have to distinguish between immutable `string` and mutable `bytes`.
This PR fixes the build for 4.06.0 and switches on `-safe-string` for all OCaml versions.
=> Fix build with OCaml 4.06.0 (and -safe-string)

src/owl/owl_stats.ml, src/owl/owl_stats.mli, test/unit_stats.ml
This change adds one and two sample Kolmogorov-Smirnov tests to `Owl.Stats`. To create my tests, I relied on a comparison with SciPy (along with reading papers/books). As a fair warning, I'm still pretty new to OCaml and Owl; apologies in advance if there are some style/mechanics issues in this PR.
=> Add Kolmogorov-Smirnov Tests to the Stats Module

src/owl/jbuild, src/owl/owl_dense_matrix_c.mli, src/owl/owl_dense_matrix_d.mli, src/owl/owl_dense_matrix_generic.mli, src/owl/owl_dense_matrix_s.mli, src/owl/owl_dense_matrix_z.mli, src/owl/owl_dense_ndarray_generic.ml, src/owl/owl_dense_ndarray_generic.mli
(I took the extreme step of deleting my fork and making a new one.  Trying to clean up a git history is a pita.  This seemed easier.  I hope it causes no problems.)
This PR adds this function:
```
(** [mpow x r] returns the dot product of square matrix [x] with itself [r] times. *)
```
The exponent `r` is a `float`, but must be a nonzero natural number.  An exception is raised otherwise.
Questions:
- Should the ocamldoc mention that only whole numbers are allowed?
- Should `mpow` handle the exponent 0.0, returning an identity matrix of the correct size?
- Have I modified all and only the right files?  I followed existing patterns, adding the signature to a number of files in order follow the same patterns (and to cause `mpow` to be included `Owl.Mat`).  I wasn't sure whether what I did in …
=> add mpow function: iterate dot prod of matrix with itself

src/owl/jbuild
Added lib path for macOS to find `openblas`.
This shouldn't affect other OS that already find `openblas`. macOS doesn't have `libopenblas.[a|dylib]` in `/usr/local/lib` or `/usr/lib`.
=> Added lib path for macOS to find openblas

src/owl/owl_neural.ml
Note that owl_neural_parallel is currently hardcoded to use single-precision arithmetic, hence can't be supported in the Neural.D module.
=> functorise owl_neural

src/owl/core/owl_ndarray.ml, src/owl/core/owl_ndarray_conv_impl.c, src/owl/core/owl_ndarray_conv_stub.c, src/owl/dense/owl_dense_common.ml
This PR adds supports of complex number for `conv` function in Owl. 
@jzstark please can you have a look to confirm the added code is consistent with your implementation? Many thanks. Also, it would be nice if you can also test a couple of very simple examples with complex number?
=> core: add complex support for conv fun

src/owl/maths/owl_maths.mli
changes are only in the doc strings of math functions. please check that the markup of math vs. code vs. displayed latex math is ok.  if yes i'll stick to it in future doc edits. 
style choice: one could also s/gives/returns everywhere.
=> start api doc review: owl_maths.mli

README.md
Update readme to add additional git option. More importantly, "homebrew/science/" is now depreciated and many of the modules have just been added to the core tap. So I updated the command to reflect the new location.
=> Small Change to Readme - Homebrew + git

src/zoo/owl_zoo_ver.ml
This PR fixes the `tol` parameter issue as discussed in #242. Current implementation only updates a gist's timestamp when a version is downloaded; the code here makes the timestamp also be updated every time Zoo sends a request to Gist server checking newest version.
=>  fix `tol` parameter logic in zoo name

src/owl/core/owl_ndarray_conv.ml, src/owl/core/owl_ndarray_conv_impl.h, test/unit_conv3d_generic.ml
This PR adds two new implementations for the convolution operations: [memory-efficient convolution](https://arxiv.org/abs/1706.06873), and a naive way of implementing them using multiple for-loops. Both have passed the convolution unittest. The current convolution ops in `Ndarray` module still use the existing `im2col` implementation.
=> Add memory-efficient and naive implementations of convolution operations

src/owl/core/owl_ndarray_conv_impl.h
The previous PR #267 applied some minor optimisation on convolution operations in the existing `im2col` implementation. I just found it has caused compile error in openmp mode. This PR rolls back the previous implementation. I'm very sorry for not having done a thorough check on my code.
=> Fix conv compile error in openmp mode

src/owl/cblas/owl_cblas_basic.ml, src/owl/lapacke/owl_lapacke.ml
This PR removes the need for `[@warning "-6"]` in `owl_lapacke.ml` and `owl_cblase_basic.ml` by explicitly labeling all the arguments. While it has no immediate value beyond readability, it may reduce friction when maintaining these modules in the future.
=> use explict labels in cblas and lapack modules

examples/checkpoint.ml, examples/feedforward.ml, examples/kmeans.ml, examples/lazy_eval.ml, examples/opencl_01.ml, examples/opencl_04.ml, examples/opencl_05.ml, examples/opencl_06.ml, examples/opencl_07.ml, examples/svm.ml
This pullreq fix some examples: maybe because of the change of signature, typing failed.
See commit log for the detail.
Other errors remain in examples:
- test_lda.ml, tfidf.ml
data is missing even after execution of `Owl.Dataset.download_all`
- test_log.ml, computation_graph_01.ml, computation_graph_02.ml
typing error
- opencl_03.ml
abort due to `Exception: Owl_opencl_generated.EXN_MEM_OBJECT_ALLOCATION_FAILURE.`
- opencl_cifar.ml
segmentation fault
- opencl_context.ml
The implementation of Owl_opencl_context.eval`  seem to have a bug. I will make another issue.
=> Fix examples

src/owl/stats/owl_stats.ml, src/owl/stats/owl_stats.mli
This PR adds a function to compute [tukey fences](https://en.wikipedia.org/wiki/Outlier#Tukey's_fences):
`val tukey_fences : ?k:float -> float array -> float * float`
Given an array of floats, it determines the lower and upper bounds for non outlier values.
=> tukey fences implementation

README.md, docker/Dockerfile.alpine, docker/Dockerfile.centos, docker/Dockerfile.debian, docker/Dockerfile.fedora, docker/Dockerfile.opensuse, docker/Dockerfile.ubuntu, docker/Dockerfile.ubuntu.arm
This minor PR renames some remaining dangling references from `jbuilder` to `dune` in the `README.md` and docker related files.
=> rename jbuilder to dune in readme and docker files

src/base/maths/owl_base_maths.ml, src/base/maths/owl_base_maths.mli, src/owl/maths/owl_maths.h, src/owl/maths/owl_maths.ml, src/owl/maths/owl_maths.mli, src/owl/maths/owl_maths_special.ml, src/owl/maths/owl_maths_special_impl.c, src/owl/maths/owl_maths_special_stub.c
Adds the log1mexp and log1pexp functions for accurate computation of log(1 + exp(x)) and log(1 - exp(x)), respectively:
https://cran.r-project.org/web/packages/Rmpfr/vignettes/log1mexp-note.pdf
=> Add log1mexp and log1pexp

src/owl/stats/owl_stats_dist_beta.c, src/owl/stats/owl_stats_dist_binomial.c, src/owl/stats/owl_stats_dist_chi2.c, src/owl/stats/owl_stats_dist_exponential.c, src/owl/stats/owl_stats_dist_exponpow.c, src/owl/stats/owl_stats_dist_gamma.c, src/owl/stats/owl_stats_dist_gaussian.c, src/owl/stats/owl_stats_dist_gumbel1.c, src/owl/stats/owl_stats_dist_gumbel2.c, src/owl/stats/owl_stats_dist_laplace.c, src/owl/stats/owl_stats_dist_logistic.c, src/owl/stats/owl_stats_dist_lognormal.c, src/owl/stats/owl_stats_dist_lomax.c, src/owl/stats/owl_stats_dist_rayleigh.c, src/owl/stats/owl_stats_dist_t.c, src/owl/stats/owl_stats_dist_vonmises.c, src/owl/stats/owl_stats_dist_wald.c, src/owl/stats/owl_stats_dist_weibull.c
Improves numerical accuracy of the statistical distributions to help dealing with small probabilities. Previously for example
`Owl.Stats.binomial_logpdf 1 ~p:0.5 ~n:2000`
would return -infinity, whereas now it returns `-1378.69345866034632`.
=> Improve numerical accuracy in stats distributions

src/base/neural/owl_neural_graph.ml, src/base/neural/owl_neural_graph_sig.ml, src/base/neural/owl_neural_neuron.ml, src/base/neural/owl_neural_neuron_sig.ml
More generalised version of the `Lambda` layer, with an arbitrary output shape and a function lambda that takes an array of node as an argument (instead of a single node).
Signed-off-by: pvdhove <pierre.vdhove@gmail.com>
=> Implementation of Lambda Array neuron in neural module

src/base/misc/owl_utils.ml, src/base/misc/owl_utils_heap.ml, src/base/misc/owl_utils_heap.mli, src/owl/dense/owl_dense_matrix_generic.mli, src/owl/dense/owl_dense_ndarray_generic.ml, src/owl/dense/owl_dense_ndarray_generic.mli, test/unit_dense_ndarray.ml
Fixes Issue #305.
Implementation of a min-heap using an array representation.
Use of this min-heap to improve the time complexity of functions `top x k` and `bottom x k` in the Ndarray module, from O(n * k) to O(n * log(k)).
The time taken by these functions is now much more predictable.
The worst case for `top` is when the ndarray is initially sorted in increasing order. This improvement can be tested with the following example:
```
let arr = Dense.Ndarray.D.init [|1000000|] (fun i -> float i) in
let result = Dense.Ndarray.D.top arr 100000 in
...
```
This used to take several minutes on my laptop, but it now takes only a few seconds.
=> Implementation of heap + improved top and bottom + tests

examples/lazy_mnist.ml, src/base/compute/owl_computation_cpu_device.ml, src/base/compute/owl_computation_cpu_eval.ml, src/base/compute/owl_computation_cpu_init.ml, src/base/compute/owl_computation_operator.ml, src/base/compute/owl_computation_operator_sig.ml, src/base/compute/owl_computation_optimiser.ml, src/base/compute/owl_computation_shape.ml, src/base/compute/owl_computation_symbol.ml, src/base/compute/owl_computation_type.ml, src/base/compute/owl_computation_type_sig.ml, src/base/neural/owl_neural_compiler.ml, src/base/neural/owl_neural_graph.ml, src/base/neural/owl_neural_graph_sig.ml, src/base/neural/owl_neural_neuron.ml
This PR adds
- `Delay`/`DelayArray` operations to the Computation Graph, to delay the evaluation of a function that is not tracked by CG. It would work to just call them `Lambda`/`LambdaArray` - however, in case the argument of the `Lambda` layer contains only supported operations, it would hide that function from CG (for example, the `lazy_mnist.ml` example would be slightly less efficient), so I think it is good to keep both kinds of operations.
- `model`/`model_inputs` functions in `owl_neural_compiler.ml` to provide an interface to optimise inference with CG as well. Note: something I don't like is that after copying the network (just like the standard `model` function in `owl_neural_graph.ml`), `Copy` nodes are created in the graph for every constant values. I am unsure if this is …
=> Add Delay operation to CG and optimised inference to neural_compiler.ml

examples/lazy_mnist.ml, src/base/neural/owl_neural_compiler.ml
Improvement of a previous PR for inference with the computation graph. The parameter `batch_slice` of `model_inputs` was misleading, but it now really performs inference batch by batch. This greatly reduces the memory used for the inference part of the `lazy_mnist.ml` example.
Two notes:
- the memory used at the end of `lazy_mnist.ml` is the sum of the memory for training and the memory for inference (roughly 800Mb + 100Mb). Calling `Gc.full_major ()` after training solves that problem, but I don't know if you estimate that this is a problem and what would a clean way of solving it.
- if `batch_slice` does not divide the input's first dimension, then the inference for the last batch performs useless calculations (because the size of the network is fixed, so I can't perform a calculation …
=> Batch inference with CG

src/base/compute/owl_computation_cpu_device.ml, src/base/compute/owl_computation_cpu_engine.ml, src/base/compute/owl_computation_cpu_eval.ml, src/base/compute/owl_computation_cpu_init.ml, src/base/compute/owl_computation_graph.ml, src/base/compute/owl_computation_optimiser.ml, src/base/compute/owl_computation_symbol.ml, src/base/compute/owl_computation_symbol_sig.ml, src/base/compute/owl_computation_type.ml, src/base/compute/owl_computation_type_sig.ml, src/base/misc/owl_utils_multimap.ml, src/base/misc/owl_utils_multimap.mli, src/base/misc/owl_utils_stack.ml, src/base/neural/owl_neural_compiler.ml, src/base/neural/owl_neural_graph.ml, src/base/types/owl_types_computation_device.ml, src/base/types/owl_types_ndarray_mutable.ml, test/test_runner.ml, test/unit_multimap.ml
This PR consists of:
- A Multimap implementation in `Owl_utils` (extension of OCaml's `Map` which allows the same key to be bound to multiple values) and one small test file for this structure (+ a small fix of `owl_utils_stack.ml`).
- A change of the `vnode` parameter of CG's nodes to a more general type `block`. A `block` holds the reference to an ndarray of fixed size. Multiple nodes can share the same block.
- A new algorithm to initialise the memory of the computation graph (inspired by [the one used by MxNet](https://mxnet.incubator.apache.org/architecture/note_memory.html#memory-allocation-algorithm)). The main idea is that during a graph traversal in evaluation order, we can spot a node which doesn't need its value anymore by keeping a counter of how many children still have to …
=> New memory optimisation algorithm for CG (+ block attribute, multimap)

owl.opam, src/owl/config/configure.ml, src/owl/config/dune, src/owl/dune
The `configurator` package has been replaced by the `dune.configurator` library. This PR changes owl to use the latter.
=> Switch to dune.configurator

src/base/compute/owl_computation_graph.ml, src/base/compute/owl_computation_optimiser.ml, src/base/core/owl_graph.ml, src/base/neural/owl_neural_compiler.ml, src/base/neural/owl_neural_graph_sig.ml
- Modified the optimisation for the `Copy` nodes in CG module: by design, these nodes are always useless (not only when their parent has only one child) since memory allocation is handled by the engine and no operation actually mutates an output value.
- Removed a useless network copy in `model_inputs` (inference with CG).
- The function `graph_to_dot` had quadratic time complexity, it is now linear (`lazy_lstm.ml` dot graph used to take more than 10 seconds to be generated, it now takes less than one second).
- The 'PostOrder BFS' from a previous PR is actually not working because PostOrder evaluation requires a recursive implementation which is not suited for a BFS.
=> Copy node optimisation and small fixes

src/base/compute/owl_computation_cpu_eval.ml, src/base/compute/owl_computation_operator.ml, src/base/compute/owl_computation_operator_sig.ml, src/base/compute/owl_computation_optimiser.ml, src/base/compute/owl_computation_shape.ml, src/base/compute/owl_computation_symbol.ml, src/base/compute/owl_computation_type.ml, src/base/compute/owl_computation_type_sig.ml, src/base/core/owl_lazy.mli
Printing the outputs of intermediate nodes in a computation graph is not possible because there is currently no way to make the print lazy, which makes debugging quite hard. I've added a `LazyPrint` node which is an identity node having the side effect of printing the output of its parent when evaluated (same trick as [TensorFlow Print()](https://www.tensorflow.org/versions/r1.11/api_docs/python/tf/Print)).
The way to use it is to insert it after the node whose output you want to print, for instance
```
module Engine = Owl_computation_cpu_engine.Make(Dense.Ndarray.S)
let x =
Engine.gaussian [|100; 100|]
|> Engine.sqr
|> Engine.lazy_print ~max_row:5 ~max_col:5
|> Engine.floor
in
Engine.eval_arr [|x|]
```
You can also use it in a neural network using CG quite easily, by putting it in a …
=> Print node in CG module

src/base/optimise/owl_algodiff_generic.ml
I modified the reverse-mode gradient of algodiff matrix inverse, changing the element-wise multiplication `*` to matrix mulitiplication `*@`.
=> fixed reverse-mode gradient of algodiff `Maths.inv`

src/base/optimise/owl_algodiff_generic.ml, src/base/optimise/owl_algodiff_generic_sig.ml, test/unit_algodiff_matrix_generic.ml
1. modified type `DR` in algodiff to track when to update adjval of inputs in reverse-mode e.g. `Algodiff.D.Maths.qr` now has type `t ->  t*t`
2. `FDGrad_test`: a new functor in algodiff that takes a module of user-specified parameters and can be used to test gradients (i.e. compare reverse-mode gradients with finite difference approximations)
=> simpler way to deal with multi-output functions in reverse-mode + expose gradient test to user

src/base/compute/owl_computation_operator.ml, src/base/compute/owl_computation_operator_sig.ml, src/base/dense/owl_base_dense_ndarray_d.mli, src/base/dense/owl_base_dense_ndarray_generic.ml, src/base/dense/owl_base_dense_ndarray_generic.mli, src/base/dense/owl_base_dense_ndarray_s.mli, src/base/optimise/owl_algodiff_generic.ml, src/base/optimise/owl_algodiff_generic_sig.ml, src/base/types/owl_types_ndarray_basic.ml, src/owl/dense/owl_dense_ndarray.ml, test/unit_algodiff_matrix_generic.ml
1. implemented reverse-mode gradient for thin `svd` and `chol`
2. minor changes in algodiff unit test to improve numerical stability of tests for `inv` and `tan`
=> Thin SVD and Chol reverse-mode gradient + minor changes in algodiff unit test

src/base/optimise/owl_algodiff_generic.ml, src/owl/linalg/owl_linalg_generic.ml
The current implementation of `logdet` returns `nan` in cases where `getrf` returns `a`, `ipiv` and `a` has negative diagonal elements. I fixed this by taking the summing the log of the absolute values of the diagonal and keeping track of the sign of the determinant. If the sign of the determinant is negative, `logdet` fails with an error.
=> minor changes in logdet

src/base/core/owl_graph.mli, src/base/misc/owl_pretty.mli, src/base/neural/owl_neural_graph_sig.ml, src/base/optimise/owl_algodiff_generic_sig.ml, src/base/stats/owl_base_stats.mli, src/owl/dense/owl_dense_ndarray_generic.mli, src/owl/nlp/owl_nlp_vocabulary.mli, src/owl/sparse/owl_sparse_matrix_generic.mli, src/owl/sparse/owl_sparse_ndarray_generic.mli, src/owl/stats/owl_stats.mli
This will make the pretty printers automatically installed
in recent versions of utop (and hopefully further toplevels,
like jupyter, will follow). Practically it means that owl-top is
no longer necessary for utop to pretty print owl values.
See e.g. https://github.com/ocaml/opam-repository/pull/13348
=> owl: add toplevel_printer annotation

owl.opam, src/owl/sparse/owl_sparse_common.ml
This is a compilation fix for the release of `eigen` 0.1.0. You need to use this it if you are pinning the eigen dev-repo.
Please wait until https://github.com/ocaml/opam-repository/pull/13407 is merged.
=> owl: update bounds on eigen

.travis.yml, owl-base.opam
All tests require owl, this was coming from a leftover commit in the previous PR. Apologies
=> Fix Travis, part2: disable owl-base tests (all tests require owl)

owl-aeos.opam, owl.opam, src/aeos/config/configure.ml, src/aeos/config/dune, src/owl/config/configure.ml, src/owl/config/dune
write_sexp is already bundled in `dune`.
=> owl,owl-aeos: remove unnecessary sexplib dependency

owl.opam, src/owl/config/configure.ml
This can simplify life when errors like https://github.com/owlbarn/owl/issues/389 happen, even if it will not be enough lots of times.
=> configurator: fail with a useful error and lower bound dune version

src/owl/core/owl_ndarray_maths.ml, src/owl/core/owl_ndarray_maths_stub.c, src/owl/dense/owl_dense_matrix_d.mli, src/owl/dense/owl_dense_matrix_generic.mli, src/owl/dense/owl_dense_matrix_s.mli, src/owl/dense/owl_dense_ndarray_d.mli, src/owl/dense/owl_dense_ndarray_generic.ml, src/owl/dense/owl_dense_ndarray_generic.mli, src/owl/dense/owl_dense_ndarray_s.mli
I'm reopening the PR for adding lgamma with a cleaner commit histroy.
Here I'm using `owl_cephes`'s `lgam` for the implementation of double-precision and the default c option `lgammaf` for single-precision. 
Note that the scalar `loggamma` function in the `Maths` module also uses `owl_cephes`'s `lgam` function.
Currently the single and double precision `lgamma` gives similar results up to around 8 decimal points.
We might consider including single-precision `cephes` functions in the future.
=> added lgamma function

.travis.yml, src/owl/config/configure.ml
With the updated conf-openblas recently merged to the opam-repository, Fedora can now be used with owl seamlessly. This PR properly re-enables Fedora tests.
=> Fedora works!

README.md, src/aeos/config/configure.ml, src/owl/config/configure.ml
This should help fixing https://github.com/owlbarn/owl/issues/354 and https://github.com/owlbarn/owl/issues/394
Would it make any sense to unify owl and aeos cflags or it is better to keep them separate?
Is there any modification you would like to have for the current default values?
=> config-flags: allow to customise owl and owl_aeos cflags

src/base/compute/owl_computation_operator.ml, src/base/compute/owl_computation_operator_sig.ml, src/base/dense/owl_base_dense_ndarray_d.mli, src/base/dense/owl_base_dense_ndarray_generic.ml, src/base/dense/owl_base_dense_ndarray_generic.mli, src/base/dense/owl_base_dense_ndarray_s.mli, src/base/optimise/owl_algodiff_generic.ml, src/base/optimise/owl_algodiff_generic_sig.ml, src/base/types/owl_types_ndarray_basic.ml, src/owl/dense/owl_dense_ndarray.ml, test/unit_algodiff_matrix_generic.ml
Implemented reverse-mode differentiation for `linsolve` and `lq` and relevant unit tests
`linsolve` is used to solve equations of the form `Ax = b`.
=> added linsolve and lq reverse-mode differentiation

src/base/types/owl_types_operator.ml, src/owl/linalg/owl_linalg_c.mli, src/owl/linalg/owl_linalg_d.mli, src/owl/linalg/owl_linalg_generic.ml, src/owl/linalg/owl_linalg_generic.mli, src/owl/linalg/owl_linalg_s.mli, src/owl/linalg/owl_linalg_z.mli
1. Added a `solve_triangular` function to the `Linalg` modules. This function efficiently solves linear equations of the form `Ax = b`, where `A` is is a triangular matrix. Under the hood, the function calls the cblas function `trsm`.  
2. Added an option to call the `solve_triangular` function to `linsolve`.  
e.g. ``linsolve ~trans ~typ:`u a b`` will call ``solve_triangular ~trans ~upper:true a b``.
=> implemented solve triangular

src/base/optimise/owl_algodiff_generic.ml
This PR fixes a bug that leads to error in running `newton_method.ml` and `regression.ml` examples. Thanks Pratap Singh for finding out the issue, and @tachukao for double-checking this solution.
=> Fix Algdiff bug

src/owl/dense/owl_dense_ndarray_generic.ml
Following the recent change of Owl exception system, this PR enhances the exceptions in convolution operations with meaningful information. Next I will similarly update the exceptions in the convolution operations in `base`.
=> Update exceptions in convolution operations

bin/owl_bin_zoo.ml, src/owl/misc/owl_dataset.ml, src/owl/owl.ml
I believe that libraries should not come with unexpected surprises, in particular I think that the main owl library should not create files in the system and instead file creation should be triggered by the user action (like downloading something from the zoo or a dataset). The creation of .owl/dataset and .owl/zoo has been moved to the zoo cli and the Dataset.load_data_path functions instead.
This change will also allow to run tests (at least some of them) inside
the opam sandboxed envirionment. In fact this is how I found out about
this.
Note that checking the existence of a folder and then creating it is racy (imagine you are downloading something in the zoo in a terminal and getting two datasets from two different instances of utop or jupyter).
The parenthesis around the try are …
=> Do not create .owl folder when loading owl library

src/base/misc/owl_io.ml
Should fix https://github.com/owlbarn/owl/issues/422
I have checked the uses of `Marshal`, it seems to be the only place where we use `to_string`.
Would be good to try and reproduce the issue independently of this and raise an issue for the ocaml compiler if `Marshal` is the one being wrong.
=> Owl_io.marshal_to_file: use to_channel

src/owl/stats/owl_stats_ziggurat.c
Fixes #426  and fixes the inconsistency in the meaning of `lambda` for the exponential distribution between owl base and owl c; since it usually refers to the inverse mean, I modified zaggurat, not base.
=> Fix exponential rvs

src/owl/config/configure.ml
string_of_sexp is the wrong function to convert sexps of strings. This
function attempts to parse an Atom sexp into a single string. Instead,
Sexp.to_string will render the sexp.
=> Fix crash when printing error message

src/owl/stats/owl_stats.mli, src/owl/stats/owl_stats_dist.ml
As described in #347, balance_last raises exceptions in case where
numerical inaccuracy prevent summation to 1 of input
probabilities. The comments there argue that not only the
transformation performed by balance_last, but is also not really
necessary. See notably this comment:
As I see it, owl's current implementation is very close to the one in
the GSL. It computes the sum of input probabilities (norm variable),
and it seems to me that it doesn't matter that these sum to 1. Playing
with gsl confirms it:
```ocaml
- : int array = [|33251; 66749|]
```
This seems very natural to me, and much less confusing and error prone
than ignoring the last element of the probability vector.
So in summary, it would be enough to remove the call to balance_last
in multinomial_rvs:
```ocaml
let …
```
=> Stats_dist: don't use balance_last for multinomial distribution (#347)

src/base/compute/owl_computation_operator.ml, src/base/compute/owl_computation_operator_sig.ml, src/base/dense/owl_base_dense_ndarray_c.mli, src/base/dense/owl_base_dense_ndarray_d.mli, src/base/dense/owl_base_dense_ndarray_generic.ml, src/base/dense/owl_base_dense_ndarray_generic.mli, src/base/dense/owl_base_dense_ndarray_s.mli, src/base/dense/owl_base_dense_ndarray_z.mli, src/base/types/owl_types_ndarray_basic.ml
This will be useful for writing functors that take input module type `Owl_types_ndarray_algodiff.Sig`.
=> expose expand and squeeze in ndarray type

src/base/algodiff/owl_algodiff_ops.ml, test/unit_algodiff_matrix_generic.ml
1. added algodiff grad test for `pow`
2. do not recalculate `cp` when calculating gradients for `pow`
=> add pow algodiff mat test + calculate cp once

src/owl/nlp/owl_nlp_tfidf.mli
Without the space it renders wrong:
=> add missing space

src/owl/nlp/owl_nlp_vocabulary.mli
the function return `(int * string)` not `(string * int)`
=> correct documentation

src/plplot/owl_plot.ml
Hi.
This patch will fix the following problem.
(Please review carefully because I'm new to this library as well as to OCaml ;)
Functions of the plot module could cause crashes.
This can be reproduced e.g. by just using `plot_fun` as in the [tutorial](https://github.com/owlbarn/owl/wiki/Tutorial:-How-to-Plot-in-Owl%3F).
```OCaml
Plot.plot_fun Maths.sin 1. 3.14;;
```
With no output filename specified, PLplot asks the output device first, and then the filename.
In my environment without this patch, the program crashes just after entering the device number.
The output looks like below.
```
Plotting Options:
< 1> ps         PostScript File (monochrome)
... 
<22> svgcairo   Cairo SVG Driver
<23> pngcairo   Cairo PNG Driver
...
Enter device number or keyword: 23
Can't open .
...
Can't open .
*** …
```
=> Do not call plsfnam if output filename is empty

src/base/algodiff/owl_algodiff_ops.ml, src/base/algodiff/owl_algodiff_ops_builder.ml, src/base/algodiff/owl_algodiff_ops_builder_sig.ml, src/base/algodiff/owl_algodiff_ops_sig.ml, src/base/compute/owl_computation_operator.ml, src/base/compute/owl_computation_operator_sig.ml, src/base/dense/owl_base_dense_ndarray_d.mli, src/base/dense/owl_base_dense_ndarray_generic.ml, src/base/dense/owl_base_dense_ndarray_generic.mli, src/base/dense/owl_base_dense_ndarray_s.mli, src/base/types/owl_types_ndarray_basic.ml, src/owl/dense/owl_dense_ndarray.ml, src/owl/linalg/owl_linalg_d.mli, src/owl/linalg/owl_linalg_generic.ml, src/owl/linalg/owl_linalg_generic.mli, src/owl/linalg/owl_linalg_s.mli, test/unit_algodiff_matrix_generic.ml
1. Added a function `build_aiso` that can be used to build  algodiff operation that takes an array input and produces a single output. This is useful for building operations that take many arguments.
2. One such example is the  continous-time algebraic Ricatti equation, which takes four inputs and produces a single output. I've added `Owl.Algodiff.D.Linalg.care` using  `build_aiso`. 
FUTURE: 
1. use `build_aiso` to build operations such as `concatenate` 
2. `Owl.Algodiff.D.Linalg.dare`
=> function to build aiso operations + algodiff gradients for CARE

src/base/algodiff/owl_algodiff_check.ml, src/base/algodiff/owl_algodiff_core.ml, src/base/algodiff/owl_algodiff_generic.ml, src/base/algodiff/owl_algodiff_graph_convert.ml, src/base/algodiff/owl_algodiff_ops.ml, src/base/algodiff/owl_algodiff_ops_builder.ml, src/base/algodiff/owl_algodiff_ops_builder_sig.ml, src/base/algodiff/owl_algodiff_ops_sig.ml, src/base/algodiff/owl_algodiff_reverse.ml, src/base/compute/owl_computation_operator.ml, src/base/compute/owl_computation_operator_sig.ml, src/base/dense/owl_base_dense_ndarray_d.mli, src/base/dense/owl_base_dense_ndarray_generic.ml, src/base/dense/owl_base_dense_ndarray_generic.mli, src/base/dense/owl_base_dense_ndarray_s.mli, src/base/types/owl_types_ndarray_basic.ml, src/owl/dense/owl_dense_ndarray.ml, test/unit_algodiff_matrix_generic.ml, test/unit_linalg_solver.ml
1. fixed bug in `build_aiso` calculation of tangents (should pass primal input array to `df` not original inputs)
2. added forward and reverse mode gradients for sylvester 
3. `of_arrays` now support higher order gradients
4. rewrote `concatenate` using `build_aiso`
=> Sylvester Algodiff + bug fixes

src/base/dune
Came up in the opam-repository submission
=> owl-base: drop seemingly unnecessary dependency on integers

Makefile, src/owl/core/openmp/owl_ndarray_maths_fold_omp.h, src/owl/core/openmp/owl_slicing_basic_impl_omp.h, src/owl/core/owl_core.h, src/owl/core/owl_core_utils.c, src/owl/core/owl_ndarray_maths_fold.h, src/owl/core/owl_ndarray_repeat_impl.h, src/owl/core/owl_ndarray_transpose.ml, src/owl/core/owl_ndarray_transpose_impl.h, src/owl/core/owl_slicing.h, src/owl/core/owl_slicing_basic_impl.h, src/owl/core/owl_slicing_fancy_impl.h, src/owl/dense/owl_dense_ndarray_generic.ml
This PR changes number type from int32 to int64 in underlying indexing and slicing function. This change affects many c code in owl core, therefore needs careful examination before merge.
=> Fix issue #337 and #457

owl.opam
This is to check if we really need the bounds
=> Owl: relax bounds on base and stdio

owl-top.opam, owl-zoo.opam, owl.opam, src/owl/dense/owl_dense_matrix_c.ml, src/owl/dense/owl_dense_matrix_c.mli, src/owl/dense/owl_dense_matrix_d.ml, src/owl/dense/owl_dense_matrix_d.mli, src/owl/dense/owl_dense_matrix_generic.ml, src/owl/dense/owl_dense_matrix_generic.mli, src/owl/dense/owl_dense_matrix_s.ml, src/owl/dense/owl_dense_matrix_s.mli, src/owl/dense/owl_dense_matrix_z.ml, src/owl/dense/owl_dense_matrix_z.mli, src/owl/dense/owl_dense_ndarray_c.ml, src/owl/dense/owl_dense_ndarray_c.mli, src/owl/dense/owl_dense_ndarray_d.ml, src/owl/dense/owl_dense_ndarray_d.mli, src/owl/dense/owl_dense_ndarray_generic.ml, src/owl/dense/owl_dense_ndarray_generic.mli, src/owl/dense/owl_dense_ndarray_s.ml, src/owl/dense/owl_dense_ndarray_s.mli, src/owl/dense/owl_dense_ndarray_z.ml, src/owl/dense/owl_dense_ndarray_z.mli, src/owl/dune, src/owl/ext/owl_ext_dense_matrix.ml, src/owl/ext/owl_ext_dense_ndarray.ml, test/unit_dense_matrix.ml, test/unit_dense_ndarray.ml
- Added functions to load and save npy files. These functions are implemented using [npy-ocaml](https://github.com/LaurentMazare/npy-ocaml)
- For "save" functions such as `Mat.save` and `Mat.save_txt`, use labelled argument `~out` to specify file name. Currently, to save a matrix  `mat` as a text file `mat.txt` we would do something like this
```ocaml
let () = 
let mat = ... in
Mat.save_txt mat "out.txt"
```
However, `mat` often comes at the end of multiple steps of calculations, it would be convenient to  "pipe" it through `Mat.save_txt` like this
``` ocaml
let () = ... |> Mat.save_txt ~out:"mat.txt"
```
=> Save and load Npy files

src/base/neural/owl_neural_graph.ml, src/base/neural/owl_neural_graph_sig.ml, src/base/neural/owl_neural_neuron.ml, src/base/neural/owl_neural_neuron_sig.ml
This PR adds an optional output shape argument to the lambda layer in neural network. Here is a simple example:
```ocaml
open Owl
open Neural.S
open Neural.S.Graph
open Neural.S.Algodiff
let dim = 2
let time_steps = 10
let batch_size = 3
let make_network () =
input [| dim; time_steps |]
|> lambda ~out_shape:[|dim; 1|] (fun x -> Maths.get_slice [[]; []; [0]] x)
|> get_network
let nn = make_network ()
let data = Dense.Ndarray.S.ones [|batch_size; dim; time_steps |]
let result = Graph.model nn data
```
=> Update lambda layer with optional output shape

ACKNOWLEDGEMENT.md
This is for re-adding the reference to DiffSharp and Hype code that was ported to OWL Algodiff and Optimise modules. 
It was previously moved from ACKNOWLEDGEMENT.md to README.md with the following commit
https://github.com/owlbarn/owl/commit/da72252bf8e38aca515c1446de7405532d90f544#diff-0deeb0e08f77f3a24a4c8bff22e977a7
and subsequently removed from README.md with the following commit
https://github.com/owlbarn/owl/commit/493f4a5cbb1bbef75218b610badcb95717f7906d#diff-04c6e90faac2675aa89e2176d2eec7d8
Also note that Francois Berenger's acknowledgment seems to be lost in this process as well. @ryanrhymes
=> Re-add removed DiffSharp acknowledgment

src/base/neural/owl_neural_graph.ml
I noticed that `Graph.inputs` gives all inputs the name `"input_0"`. I assume nodes are expected to have unique names, so I moved the call `add_node` to right after the node creation. Does this make sense?
=> Make Graph.inputs give unique names to inputs

src/base/neural/owl_neural_graph.ml, src/base/neural/owl_neural_graph_sig.ml
This is work on https://github.com/owlbarn/owl/issues/487
This PR contains code for extracting a subnetwork from an existing network.
Some examples:
Original network:
```
let nn = Graph.(
let inp = input [| 2 |] in
let x1 = lambda ~name:"x1" ~out_shape:[|1|] (fun x -> Algodiff.Maths.get_slice [[]; [0]] x) inp in
let x2 = lambda ~name:"x2" ~out_shape:[|1|] (fun x -> Algodiff.Maths.get_slice [[]; [1]] x) inp in
let f1 = fully_connected ~name:"f1" 1 x1 in
let f2 = fully_connected ~name:"f2" 1 x2 in
let sum = add ~name:"sum" [| f1; f2 |] in
sum |> get_network)
```
```
let f1nn = Graph.get_subnetwork ~in_names:[|"x1"|] (Graph.get_node nn "f1")
```
`f1nn` can then be used in `Graph.model f1nn` with input of shape `[|1|]`. Without `~in_names`, it uses the inputs of `nn`, so in this case …
=> [WIP] Added Graph.get_subnetwork for constructing subnetworks

src/base/neural/owl_neural_graph.ml
If one mistakenly uses `Graph.model` with a multi-input nn with inputs of the same shape, the input data is duplicated. If they don't have the same shape, it hits an assert error. 
This adds a check for multi-input and suggests to use `Graph.model_inputs` if appropriate. It resolves https://github.com/owlbarn/owl/issues/484 as the other issues were due to my misunderstanding.
=> Avoid input duplication with Graph.model and multi-input nn

src/base/algodiff/owl_algodiff_core.ml, src/base/algodiff/owl_algodiff_core_sig.ml, src/base/algodiff/owl_algodiff_ops.ml, src/base/algodiff/owl_algodiff_reverse.ml
Currently,  when the forward pass involves broadcasting operations, we use `_shrink` in `owl_algodiff_reverse.ml` to make sure the adjoints have the right shape.
Because `_shrink` is not differentiable, we run into reshape/slicing errors when we try and differentiate through it to calculate higher order derivatives e.g.`hessian`.
This is not a problem when we are dealing with first-order gradients because we do not need to differentiate through `_shrink`.
In this PR, I fix this problem by removing the `_shrink` operation from `owl_algodiff_reverse.ml` and introduce a similar, but differentiable, function `_squeeze_broadcast` in `owl_algodiff_ops.ml`. This function is used to make sure that broadcast operations always return adjoints that have the right shape.
Here is a simple script that …
=> Broadcast bug for higher order derivatives

src/owl/core/owl_ndarray_maths.ml, src/owl/core/owl_ndarray_maths_stub.c, src/owl/dense/owl_dense_matrix_d.ml, src/owl/dense/owl_dense_matrix_generic.ml, src/owl/dense/owl_dense_matrix_generic.mli, src/owl/dense/owl_dense_matrix_intf.ml, src/owl/dense/owl_dense_matrix_s.ml, src/owl/dense/owl_dense_ndarray_d.ml, src/owl/dense/owl_dense_ndarray_generic.ml, src/owl/dense/owl_dense_ndarray_generic.mli, src/owl/dense/owl_dense_ndarray_intf.ml, src/owl/dense/owl_dense_ndarray_s.ml, src/owl/stats/owl_stats.h
I added a function to draw samples from a poisson distribution with rate `mu`
```ocaml
val poisson : mu:float -> int array -> Arr.arr
```
Here, I have not implemented the option to provide a `mu` of type `Arr.arr`, as suggested in #496.  
Perhaps, as future extensions,  for each the random variable functions `gaussian`, `uniform` and `poisson`, we could add the variants:
```ocaml
val gaussian_rvs : mu:Arr.arr -> sigma:Arr.arr -> int array -> Arr.arr
val uniform_rvs : a:Arr.arr -> b:Arr.arr -> int array -> Arr.arr
val poisson_rvs: mu:Arr.arr -> int array -> Arr.arr
```
where parameters `mu`, `sigma`, `a`, and `b` are broadcasted to the requested shape.
For `gaussian_rvs`, this could already easily implemented:
```ocaml
let gaussian_rvs ~mu ~sigma dims =
mu + (sigma * (gaussian dims))
```
=> Draw poisson RVs in Ndarray and Mat modules

src/base/types/owl_types_stats_dist.ml, src/owl/ppl/owl_distribution.ml, src/owl/ppl/owl_distribution.mli, src/owl/ppl/owl_distribution_common.ml, src/owl/ppl/owl_distribution_common_c.c, src/owl/ppl/owl_distribution_generic.ml, src/owl/stats/owl_stats_dist_hypergeometric.c, src/owl/stats/owl_stats_dist_poisson.c
Following the last PR #498, I've added `poisson_rvs` to `Owl_distribution_generic` and `Owl_distribution` as a module.
I've also replaced the `loggamma` function with the cephes implementation `lgam` (this was on the TODO).
On a side note, I find some of the documentation in `owl_ndarray_maths_map.h` slightly confusing. I'm still not entirely sure why `exponential_rvs` uses `FUN24` and `gaussian_rvs` uses `FUN25`. I'm using `FUN24` to define `poisson_rvs`, as like `exponential_rvs` it only has one parameter. It would be nice to have a more detailed description of these functions and maybe more informative names at some point? Just a thought.
=> Added poisson_rvs to Owl_distribution

src/base/algodiff/owl_algodiff_ops.ml, src/base/algodiff/owl_algodiff_ops_builder.ml, src/base/algodiff/owl_algodiff_ops_builder_sig.ml
In reverse mode, the gradients should be calculated using the primal of the inputs (being differentiated) as opposed to the inputs themselves. Fixed this bug for `pow` and `aiso` operations such as `sylvester` and `care`
=> Fix bug in reverse mode gradients of aiso operations and pow

src/base/algodiff/owl_algodiff_ops.ml
This PR fixes a bug in the function `_squeeze_broadcast` in `owl_algodiff_ops.ml`. 
This function is used to ensure that the dimensionality of the adjoint is compatible with that of the input in the forward pass. Currently `_squeeze_broadcast` does not accommodate valid broadcasting operations that involve inputs with different dimensions. For example, it would give a broadcasting error for the following operation
```ocaml
let x = a + b
```
where `a` has dimensions `[|2; 3; 4|]` and `b` has dimensions `[|3; 4|]`. 
As a result of this bug, `mnist_cnn.ml` and `lazy_mnist.ml` in the examples were broken.
This PR fixes this issue.
=> Fix bug in _squeeze_broadcast

owl.opam, src/base/algodiff/owl_algodiff_ops_builder.ml, src/base/core/owl_base_slicing.ml, src/base/dense/owl_base_dense_ndarray_generic.ml, src/base/neural/owl_neural_compiler.ml, src/base/neural/owl_neural_graph.ml, src/base/optimise/owl_optimise_generic.ml, src/owl/bindings/Makefile, src/owl/bindings/owl_cblas_parser.ml, src/owl/bindings/owl_lapacke_parser.ml, src/owl/cblas/owl_cblas_generated.ml, src/owl/cblas/owl_cblas_generated.mli, src/owl/core/owl_ndarray_maths.ml, src/owl/core/owl_slicing.ml, src/owl/dense/owl_dense_matrix_generic.mli, src/owl/dense/owl_dense_matrix_intf.ml, src/owl/dense/owl_dense_ndarray_a.ml, src/owl/dense/owl_dense_ndarray_generic.ml, src/owl/dense/owl_dense_ndarray_generic.mli, src/owl/dense/owl_dense_ndarray_intf.ml, src/owl/lapacke/owl_lapacke.ml, src/owl/lapacke/owl_lapacke_generated.ml, src/owl/lapacke/owl_lapacke_generated.mli, src/owl/maths/owl_maths_special.ml, src/owl/ppl/owl_distribution.ml, src/owl/working/owl_parallel.ml, src/plplot/owl_plot.ml, test/unit_algodiff_diff_generic.ml, test/unit_linalg_solver.ml, test/unit_stats_rvs.ml
This PR makes Owl compatible with the latest version of Ctypes see #489 
Changes are made to the lapacke and cblas parser and generated files as well as `owl_maths_special.ml`.
=> Owl now compatible with latest version of Ctypes

bin/owl_upload_gist.sh, examples/custom_algodiff_op.ml, examples/lazy_eval.ml, test/unit_algodiff_diff_generic.ml, test/unit_stats_rvs.ml
Typos found with https://github.com/codespell-project/codespell
I suppose the typos remaining in 'docs' will be corrected automatically.
=> Fixing typos

src/base/algodiff/owl_algodiff_ops.ml, src/base/algodiff/owl_algodiff_ops_sig.ml, test/unit_dense_ndarray.ml
The main changes in this PR are:
1. can now do Ndarray `transpose` in Algodiff, by exposing the ?axis argument
2. use `transpose` to implement `swap` in Algodiff
3. implement `kron` product using `transpose` and matrix product in Algodiff (implementation thanks to @ghennequin )
=> Added kron and swap to Algodiff operations

src/base/neural/owl_neural_graph.ml, src/base/neural/owl_neural_graph_sig.ml
Hi, I finally got around to adding this small change. This was discussed in https://github.com/owlbarn/owl/pull/491 I personally don't need it, but for the sake of completeness, here it is.
Example:
```
let nn = Graph.(
let inp = input [| 2 |] in
let x1 = lambda ~name:"x1" ~out_shape:[|1|] (fun x -> Algodiff.Maths.get_slice [[]; [0]] x) inp in
let x2 = lambda ~name:"x2" ~out_shape:[|1|] (fun x -> Algodiff.Maths.get_slice [[]; [1]] x) inp in
let f1 = fully_connected ~name:"f1" 1 x1 in
let f2 = fully_connected ~name:"f2" 1 x2 in
let sum = add ~name:"sum" [| f1; f2 |] in
sum |> get_network);;
Graph.get_subnetwork ~make_inputs:[|"x1"; "x2"|] nn [| "f1"; "f2" |];;
```
Two comments:
- I also added a flag for whether to copy the weights.
- I did change the signature (likely not many are using …
=> Graph subnetwork: Multiple outputs

src/base/misc/owl_utils_infer_shape.ml, src/base/misc/owl_utils_infer_shape.mli, src/base/neural/owl_neural_graph.ml, src/base/neural/owl_neural_graph_sig.ml, src/base/neural/owl_neural_neuron.ml, src/base/neural/owl_neural_neuron_sig.ml
A node producing a `get_slice` on its input.
Most code that is not boilerplate is for computing the output dimension. The calculation itself is pretty much the same as in `_enumerate_slice_def` (https://github.com/owlbarn/owl/blob/master/src/base/dense/owl_base_dense_ndarray_generic.ml#L99). The `assert` is a bit more aggressive (checks bounds) to avoid `Assert_failure ("src/base/core/owl_base_slicing.ml", 90, 10).` when running.
I am aware of special cases like that "later" axes do not need to be specified, and handle that. Are there others that I might have missed?
~~There is one potential extra feature: A bool flag to set whether trivial dimensions (those with length 1) should be remove, i.e., reshaped away. Is this too niche/specialized?~~
~~There is still a TODO for prettier (more …
=> Graph Slice node (resolves #483)

src/owl/misc/owl_dataset.ml
Addresses https://github.com/owlbarn/owl/issues/518
=> Fixes #518 by introducing another `/` to resolve data directory

.ocamlformat, src/base/neural/owl_neural_graph_sig.ml
As of the new release process we are implementing for ocamlformat here is the preview of what the codebase would look like after ocamlformat-0.14.2 has been applied.
This preview is not definitive, as we need to make sure it is fitting with other main ocaml projects as well, please do not merge this PR.
The .ocamlformat file has been updated for consistency (setting the ocamlformat version is advised) although the package has not been submitted to opam yet. If you wish to test this version, remove this line in the .ocamlformat file, and use the master version of ocamlformat (as of ocaml-ppx/ocamlformat@6fb5a8c)
The diff you can see can be explained by the function signature exceeding the margin.
Feel free to give your feedback on this PR or open an issue on …
=> Preview of ocamlformat 0.14.2

.ocamlformat
`after` becomes `after-when-possible` in ocamlformat version 0.14.2
=> ocamlformat: after -> after-when-possible

src/base/algodiff/owl_algodiff_ops.ml
Fixed subtraction bug in forward mode raised in #532. There pointed to a _related_ bug in the forward mode of `lyapunov`.
=> fixed bug in sub forward mode

src/base/algodiff/owl_algodiff_ops.ml, src/base/algodiff/owl_algodiff_ops_sig.ml, src/base/compute/owl_computation_cpu_eval.ml, src/base/compute/owl_computation_cpu_init.ml, src/base/compute/owl_computation_operator.ml, src/base/compute/owl_computation_operator_sig.ml, src/base/compute/owl_computation_optimiser.ml, src/base/compute/owl_computation_shape.ml, src/base/compute/owl_computation_symbol.ml, src/base/compute/owl_computation_type.ml, src/base/compute/owl_computation_type_sig.ml, src/base/core/owl_lazy.mli, src/base/dense/owl_base_dense_ndarray_generic.ml, src/base/dense/owl_base_dense_ndarray_generic.mli, src/base/dense/owl_base_dense_ndarray_intf.ml, src/base/types/owl_types_ndarray_basic.ml, src/base/types/owl_types_ndarray_mutable.ml, src/owl/dense/owl_dense_matrix_generic.ml, src/owl/dense/owl_dense_matrix_generic.mli, src/owl/dense/owl_dense_matrix_intf.ml, src/owl/dense/owl_dense_ndarray_generic.ml, src/owl/dense/owl_dense_ndarray_generic.mli, src/owl/dense/owl_dense_ndarray_intf.ml, src/owl/ext/owl_ext_dense_matrix.ml, test/unit_algodiff_matrix_generic.ml, test/unit_dense_matrix.ml, test/unit_dense_ndarray.ml
As discussed in #529, I've added the `keep_dims` option for `sum`, `mean`, `var`, `std`, `sem`, `min`, `max`, `log_sum_exp`, `prod` and others.
The default option for `keep_dims` is `true` and is thus backward compatible.
@jzstark @ryanrhymes I'm not quite sure how `keep_dims` changes the computation graph in e.g., `owl_base_computation_operation.ml`. I've ignored the `keep_dims` option for now. Any ideas?
=> keep_dims option

.ocamlformat, src/base/core/owl_operator.ml
Hi, this is what the project would look like after being reformatted with the current version (candidate) of ocamlformat 0.15.0.
**Please do not merge until ocamlformat.0.15.0 is available with opam.**
The main changes you see are due to moving the attributes moving to be placed next to the `end` keyword of classes and modules. This change has been made for the `janestreet` profile because JaneStreet is postprocessing its code with ocp-indent and having the attribute on its own line after `end` was weirdly indented by ocp-indent.
=> Upgrade to ocamlformat 0.15.0

src/base/compute/owl_computation_optimiser.ml, src/base/core/owl_operator.ml, src/base/core/owl_operator.mli, test/unit_slicing_fancy.ml
The following works:
```
let (.%[;..]) = Bigarray.Genarray.get;;
let sum x y = x.%[1;2;3] + y.%[1;2];;
```
While the following both fail with Error: Unbound value .%[]:
```
let (.%[;..]) = Bigarray.Genarray.get;;
let sum x y z = x.%[1;2;3] + y.%[1;2] + z.%[1];;
let sum x y z = x.%[1;2;3] + y.%[1;2] + z.%[1;];;
```
Defining both, e.g.
```
let (.%[;..]) = Bigarray.Genarray.get;;
let (.%[]) a v = Bigarray.Genarray.get a [|v|];;
let sum x y z = x.%[1;2;3] + y.%[1;2] + z.%[1];;
```
everything seems to work.
In owl_operator we were not defining the single accessor.
=> Fix access

src/base/optimise/owl_optimise_generic_sig.ml
While I was trying to understand the meaning of Adam learning rate update strategy parameters, I thought I could as well add what I'd found in the doc. I also fixed warnings related to {6 } and {7 } sectioning levels not being supported, and in any case one section per module is not optimal IMHO. I replaced them with module-attached descriptions, the result is better with odoc. Finally I changed code markup to `[ ... ]` which is the one supported by ocamldoc/odoc.
=> base/Optimize_sig: partial doc improvement

INSTALL_WINDOWS.md, owl.opam, src/base/misc/owl_io.ml, src/owl/core/owl_ndarray_conv_impl.h
This is a first step towards Windows compatibility. Feel free to start merging or wait for the remaining issues to be fixed, depending on your release plans.
Currently, `Owl_maths.mulmod` and `Owl_maths.powmod` crash; other tests pass. I don't see any special reason for this, but compilation warnings give hints that there are symbol clashes "around" `math.h`. I will further investigate this.
You can find some docs and status in `INSTALL_WINDOWS.md`
=> Windows compatibility

src/owl/core/owl_ndarray_contract.h, src/owl/core/owl_ndarray_contract_impl.h, src/owl/maths/owl_maths.h, src/owl/maths/owl_maths_special_impl.c, src/owl/maths/owl_maths_special_stub.c
This PR replaces `long` with `int64_t` from `<stdint.h>`. This improves portability, as according to C standard, `long` is only guaranteed to be at least 32 bit (it is 64 bit on Linux with gcc, but 32 bit with mingw on Windows). This PR fixes #550 and has been tested on Windows10/Cygwin with `x86_64-w64-mingw32-gcc` and with `gcc` on Ubuntu 20.04 (WSL2).
=> fix portability issue of 'long int'

.ocamlformat, src/base/compute/owl_computation_cpu_engine.ml, src/base/compute/owl_computation_cpu_eval.ml, src/base/compute/owl_computation_engine.ml, src/base/compute/owl_computation_shape.ml, src/base/dense/owl_base_dense_ndarray_generic.ml, src/base/neural/owl_neural_generic.ml, src/base/stats/owl_base_stats.ml, src/owl/config/configure.ml, src/owl/optimise/owl_regression.ml
Hi, this pull-request is a preview of the soon to be released ocamlformat.0.16.0. The main changes in this diff are:
- the indentation of module includes has been fixed;
- the expressions following an `if` keyword are now properly broken.
Let me now if you notice any regressions.
=> Preview of ocamlformat.0.16.0

src/base/algodiff/owl_algodiff_generic.ml, src/base/algodiff/owl_algodiff_ops.ml, src/base/algodiff/owl_algodiff_ops_builder.ml, src/base/algodiff/owl_algodiff_ops_builder_sig.ml, src/base/algodiff/owl_algodiff_ops_sig.ml, src/base/compute/owl_computation_cpu_init.ml, src/base/compute/owl_computation_operator.ml, src/base/compute/owl_computation_operator_sig.ml, src/base/compute/owl_computation_symbol.ml, src/base/compute/owl_computation_type.ml, src/base/compute/owl_computation_type_sig.ml, src/base/dense/owl_base_dense_ndarray_generic.ml, src/base/dense/owl_base_dense_ndarray_generic.mli, src/base/dense/owl_base_dense_ndarray_intf.ml, src/base/types/owl_types_ndarray_basic.ml, test/unit_algodiff_matrix_generic.ml
1. We now check that the output of `grad` and the input of `diff` are scalars (as referenced in #540)
2. There was a somewhat obscure bug in building AISO operations in Algodiff. The bug occurs when the input to an `aiso` operation (e.g. `concatenate`) include reverse-mode and forward-mode with tags at different levels. I've a new unit test `nested_grad2` in `unit_algodiff_matrix_generic.ml` to explicitly test for this.
3. I've also implemented the forward-mode derivative of `split`, which required changing `SIAO`  in `Builder`
=> Fixed bug in aiso + checks for grad and diff + forward-mode derivative for split

src/owl/fftpack/owl_fft_d.mli, src/owl/fftpack/owl_fft_generic.ml, src/owl/fftpack/owl_fft_generic.mli, src/owl/fftpack/owl_fft_s.mli
This PR adds simple implementation of 2D fft and ifft operations, as required by the example in owl book.
=> Add initial FFT 2D implementation

src/base/algodiff/owl_algodiff_ops.ml, src/base/algodiff/owl_algodiff_ops_sig.ml, src/base/compute/owl_computation_operator.ml, src/base/compute/owl_computation_operator_sig.ml, src/base/linalg/owl_base_linalg_generic.ml, src/base/linalg/owl_base_linalg_generic.mli, src/base/linalg/owl_base_linalg_intf.ml, src/base/types/owl_types_ndarray_algodiff.ml, src/owl/linalg/owl_linalg_generic.ml, src/owl/linalg/owl_linalg_generic.mli, src/owl/linalg/owl_linalg_intf.ml, test/unit_algodiff_matrix_generic.ml
This PR includes the following changes:
1. generalized derivatives of `AD.Linalg.lyapunov` and `AD.Linalg.discrete_lyapunov` to non-symmetric `Q`s
2. symmetrize `pbar` and `ptangents` in `care` because `p` is symmetric
3. added checks for the dimensions of the inputs to `care` and `dare`
4. added tests for the solutions of `care` and `dare` to make sure the solves were carried out correctly
5. added forward and reverse-mode derivatives for `dare`
=> Simplified + implemented Sylvester, Lyapunov, and Riccati derivatives

src/owl/sparse/owl_sparse_matrix_generic.ml
The dimensions are now swapped properly.
=> Fixing a big bug in sparse matrix transpose

src/owl/maths/owl_maths_special_gamma.c
When m = n or m = 0, the number of combinations should be 1, not 0.
This should Fix #587.
=> Fixed combinations.

test/unit_signal.ml
Mark a variable as unused.  
This change fixes this error when building and running tests:
```
$ dune runtest
File "test/unit_signal.ml", line 78, characters 14-15:
78 |       |> fun (a, b) -> b
^
Error (warning 27 [unused-var-strict]): unused variable a.
```
=> Mark variable as unused

src/base/algodiff/owl_algodiff_ops.ml
This is fixed by first extracting the `primal'` value.
=> unpack_arr would fail in nested forward/reverse mode

src/owl/dense/owl_dense_matrix_generic.mli
This is a tiny fix for the example for the `Owl_dense_matrix_generic.linspace` mli file documentation.
The example shows:
```
[linspace 0. 5. 5] will create a row vector [[0;1;2;3;4;5]]
```
However, that code produces `0; 1.25; 2.5; 3.75; 5`.  So I changed the example code to `linspace 0. 5. 6` to get the nice `0; 1; 2; 3; 4; 5` output.
=> Fix mli example for Owl_dense_matrix_generic.linspace

src/base/compute/owl_computation_operator.ml, src/owl/dense/owl_dense_matrix_generic.ml, src/owl/dense/owl_dense_ndarray_generic.ml
Some functions that check dimensions of the input argument raise a NOT_MATRIX exception, others raise Failure or Assert_failure.  This commit changes them to all use the same dimension checking logic and to raise a NOT_MATRIX exception.
The mli docs for these functions did not mention that they can raise exceptions, would you like me to add that info to the mli entries?
Also, now each of these functions has the same dimension check logic, maybe it would be a good idea to pull it out in its own function.  But then, maybe that should need benchmarking before doing that (though not sure if these particular functions would be in a hot path anyway...)
=> Clean up exception raising functions

src/base/misc/owl_dataframe.ml
Now the series length is equal to size not the capacity.
Fixes #654
=> fixes get_cols to return properly chopped series

src/base/misc/owl_io.ml
Executing `Owl_dataframe.of_csv "large.csv"` prints:
```
2023-04-13 14:01:52.922 WARN : Owl_io.head: ignored exception File "src/base/misc/owl_io.ml", line 138, characters 9-15: Assertion failed
```
Using assertions for control-flow (early exit of loop) seems wrong, and causes log messages to be shown on the console. Raise an [End_of_file] exception instead which will be handled by the iteration function just as if the file ended early. Use [raise_notrace] because the exception is immediately caught and we don't need a backtrace.
=> Owl_io.head: avoid log message about assertion failure on large CSV file

src/owl/config/configure.ml
ocaml/ocaml#12405 proposes using `linux` everywhere for the "system" variable. The change doesn't semantically affect the script, but it seemed worth making it clearer in the code that the two cases need to be identical.
=> Clarify that linux/linux_elf are identical systems

src/base/stats/owl_base_stats_dist_gaussian.ml, src/base/stats/owl_base_stats_dist_uniform.ml, src/owl/stats/owl_stats_ziggurat.c
Draft pull request because the following unit test fails (but it also fails before any of my changes):
```
File "test/unit_stats_rvs.ml", line 757, character 2:
FAIL Avg ppf error in 'gamma_shape_0.900000_scale_1.000000' <1E-28
Expected: `true'
Received: `false'
Raised at Alcotest_engine__Test.check in file "src/alcotest-engine/test.ml", line 200, characters 4-261
Called from Dune__exe__Unit_stats_rvs.test_rough_cdf in file "test/unit_stats_rvs.ml", line 757, characters 2-107
Called from Stdlib__List.iter in file "list.ml", line 110, characters 12-15
Called from Dune__exe__Unit_stats_rvs.test_rough_cdf_matches in file "test/unit_stats_rvs.ml", line 779, characters 2-45
Called from Alcotest_engine__Core.Make.protect_test.(fun) in file "src/alcotest-engine/core.ml", line 181, characters …
```
=> Avoid calling `log(0)` when generating gaussian random variables

.github/workflows/ci.yaml, test/dune
This tests separately the three packages, should catch packaging issues before releases are made. It also tests the arm builds for macos (they will fail until https://github.com/owlbarn/owl/pull/609 is merged)
=> Enable github actions for testing

.github/workflows/mac.yml, .github/workflows/main.yml
As an aside, I have no idea why we install `aspcud`
=> Update mac.yml: fix pkg-config issue

.github/workflows/os.yml, owl-base.opam, owl-top.opam, owl.opam
And later we could switch to 5.3, to ensure compatibility with recent compilers
=> .os.yml: drop support for 4.12, check also 5.2
